# docker-compose.yml
version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: iot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iot_monitoring
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - iot-network

  # Mosquitto MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: iot-mosquitto
    restart: always
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSockets port
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto-data:/mosquitto/data
      - ./mosquitto/mosquitto-log:/mosquitto/log
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge